Wite a Python function that takes two three-dimensional numeric data sets and ads them componentwise.

In [ ]:
def addcomponentwise(a,b):
    if len(a) != 3 or len(b) != 3:
        raise ValueError("Both inputs must be three-dimensional tuples.")
    x1,y1,z1=a
    x2,y2,z2=b

    return (x1+x2,y1+y2,z1+z2)

a=(1,2,3)
b=(5,6,7)
addcomponentwise(a,b)

(6, 8, 10)

Write a Python program for a matrix class that can add and multiply two-dimensional arrays of numbers, assuming the dimensions agree appropriatly for the operation.

In [15]:
import numpy as np
class Matrix:
    def __init__(self,a,b):
        self.matrix1=a
        self.matrix2=b
        print(a)
        print(b)
    def add(self):
        if self.matrix1.shape != self.matrix2.shape:
            raise ValueError("The dimensions didn't match")

        return self.matrix1+self.matrix2
    
    def multiply(self):
        if self.matrix1.shape != self.matrix2.shape:
            raise ValueError("The dimensions didn't match")
        
        return np.dot(self.matrix1,self.matrix2)



a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

matrix=Matrix(a,b)
# matrix.add()
matrix.multiply()

[[6 1]
 [3 6]]
[[8 5]
 [7 9]]


array([[55, 39],
       [66, 69]])